// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZriC__tkFop4Q6xrI6Q3ql2tUroitYE',
    appId: '1:927257078359:web:e55cb674c0341e1f669112',
    messagingSenderId: '927257078359',
    projectId: 'chaicycle-b3af4',
    authDomain: 'chaicycle-b3af4.firebaseapp.com',
    storageBucket: 'chaicycle-b3af4.firebasestorage.app',
    measurementId: 'G-FPW27T60V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBToeN72b3SCl-omDJ2w0eVGOAeanSTLvw',
    appId: '1:927257078359:android:16eaa54ea39853f3669112',
    messagingSenderId: '927257078359',
    projectId: 'chaicycle-b3af4',
    storageBucket: 'chaicycle-b3af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0ZVDgdSOPjhBEPaWLkOBmh7BQNb1qSs',
    appId: '1:927257078359:ios:21ca5d530caa9240669112',
    messagingSenderId: '927257078359',
    projectId: 'chaicycle-b3af4',
    storageBucket: 'chaicycle-b3af4.firebasestorage.app',
    iosBundleId: 'com.example.chaicycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0ZVDgdSOPjhBEPaWLkOBmh7BQNb1qSs',
    appId: '1:927257078359:ios:21ca5d530caa9240669112',
    messagingSenderId: '927257078359',
    projectId: 'chaicycle-b3af4',
    storageBucket: 'chaicycle-b3af4.firebasestorage.app',
    iosBundleId: 'com.example.chaicycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGZriC__tkFop4Q6xrI6Q3ql2tUroitYE',
    appId: '1:927257078359:web:49eae38cc8778d1e669112',
    messagingSenderId: '927257078359',
    projectId: 'chaicycle-b3af4',
    authDomain: 'chaicycle-b3af4.firebaseapp.com',
    storageBucket: 'chaicycle-b3af4.firebasestorage.app',
    measurementId: 'G-YX9BYBZVEN',
  );
}
